### PR TITLE
Fix bin path

### PR DESCRIPTION
**Pull request by brettz9**
This is apparently what is needed for #38

### CODE REVIEW

**Comment by FRSgit** [comment]
Thanks for resolving this issue!
Don't worry about the CI error though - guys from tmp-promise must've done some commit amending or sth, because locally after clearing yarn's cache - it works again. I will fix that on master branch. Cheers!

**Comment by FRSgit** [comment]
Btw. for now use the package from github's master branch. This fix will be available in next release, but I want make dependencies upgrade before that and resolving compatibility issues probably will take me a while.

**Comment by brettz9** [comment]
Great, thanks!

And in case it is feasible, hint, hint, I'm eager if you can get that glob output enhancement! (#4) :)

**Comment by FRSgit** [comment]
Upgrading dependencies will be my main focus right now, but next thing might be #4, why not. Also, if you want you're more than welcome to file a PR with these changes as well! 😄

**Comment by FRSgit** [comment]
Hey, just finished work on dependency upgrades & better parallelisation, now it's time for #4! Any ideas on how that should work?
(BTW. can u star this repo please? 😄)

**Comment by FRSgit** [comment]
BTW. 2 - when upgrading dependencies I've faced one breaking change coming from `fast-glob` package, please look at [changelog](https://github.com/FRSource/FRS-replace/blob/master/CHANGELOG.md) for migration info.

**Comment by brettz9** [comment]
It turns out I didn't need the multi-output after all (I have different replacements I need to make in each), so I just piped them, but your library is now saving me from a `cp` (over `replace-in-file`).

Anyways, repo well-deservingly starred! :)

Though as mentioned I'm not looking for it now, if you needed ideas for multi-output, I guess besides flat or nested exact name copies, one might want to add a prefix, suffix, template (for adding infixes), esp. if copying within the same directory. But things like this can get tricky and sometimes easier to understand by keeping it simple anyways. But if a need comes up, I may come knocking! :)

**Comment by FRSgit** [comment]
Really glad that this package is helpful to you! Sure, give me a sign if you need that/have other ideas worth sharing.
Well - I'm starting to think that maybe will be better to just provide few hooks, so it will be possible to create plugins for things like this output (prefixes/suffixes, etc). So adding support for plugins and creating one plugin specially for this should be easier (and won't affect performance for any other use-case). But I need to think more about this one before making a decision.

**Pull request merged**
